version: '3.8'
services:
    test:
        network_mode: host
        image: close_approach_robot
        shm_size: "256M"
        environment:
            USERNAME: kejak
        volumes: [
           "./suites:/suites",
           "./scripts:/scripts",
           "./output:/output",
           "./resources:/resources"
        ]